#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
npx lint-staged

# Run tests
npm run test

# Check for hardhat security
npx hardhat check

# Check for sensitive data
npx secretlint
